version: 2
updates:
#   - package-ecosystem: "npm"
#     directory: "/"
#     versioning-strategy: auto
#     schedule:
#       interval: "monthly"
#     assignees:
#       - "roryclaasen"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "roryclaasen"
