# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches: [ node.js ]
  pull_request:
    branches: [ node.js ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
      
  deploy:
    needs: build
    if: github.ref != 'refs/heads/node.js'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build
    - name: Has Changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        now=$(date)
        git add readme.md
        git commit -m "[ci skip] Deploying latest changes ($now)"
        version=$(npm version patch)
        git reset --soft HEAD~2
        git commit -m "[ci skip] $version (Build $TRAVIS_BUILD_NUMBER at $now)"
        git tag -fa $version -m $version
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: node.js
    - name: Push tags
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: node.js
        tags: true
