name: Node.js CI

on:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches-ignore: [python]
  pull_request:
    branches-ignore: [python]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        name: node-${{ matrix.node-version }}-build-artifact
        path: dist/
      
  deploy:
    needs: build
    if: github.ref == 'refs/heads/node.js'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm run build
    - name: Has Changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    - name: Commit Changes
      if: steps.changes.outputs.changed == 1
      run: |
        git config --local user.email "2751799+roryclaasen@users.noreply.github.com"
        git config --local user.name "Rory Claasen [Bot]"
        now=$(date)
        git add readme.md
        git commit -m "[ci skip] Deploying latest changes ($now)"
        version=$(npm version patch)
        git reset --soft HEAD~2
        git commit -m "[ci skip] $version (Build $TRAVIS_BUILD_NUMBER at $now)"
        git tag -fa $version -m $version
    - name: Push changes
      if: steps.changes.outputs.changed == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: node.js
    - name: Push tags
      if: steps.changes.outputs.changed == 1
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: node.js
        tags: true
