name: Update Version

on:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - main
    tags-ignore: ["v**"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hasChanged: ${{ steps.changes.outputs.changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12
      - name: Restore Dependency Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run start
      - name: Test Package
        run: npm test
      - name: Set Has Changed
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

  deploy:
    needs: build
    if: needs.build.outputs.hasChanged == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Use Node.js 12
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12
      - name: Restore Dependency Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build Package
        run: npm run start
      - name: Commit Changes
        run: |
          git config --local user.email "2751799+roryclaasen@users.noreply.github.com"
          git config --local user.name "Rory Claasen [Bot]"
          now=$(date)
          git add readme.md
          git commit -m "Updates readme with latest changes"
          version=$(npm version patch)
          git reset --soft HEAD~2
          git commit -m "Updates version to $version"
          git tag -fa $version -m $version
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: main
          tags: true
